version: '2.1'

volumes:
  spotifycache:
  adguardhome_work:
  adguardhome_conf:

services:
  ##### AdGuard
  # https://hub.docker.com/r/adguard/adguardhome
  adguard:
    image: adguard/adguardhome:v0.107.7
    network_mode: host
    privileged: true
    volumes:
        - 'adguardhome_work:/opt/adguardhome/work:rw'
        - 'adguardhome_conf:/opt/adguardhome/conf:rw'
    command: --host 0.0.0.0 --port 80 --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml

  ##### balena sound
  # Core services
  # -- Required for a fully featured installation of balenaSound
  # -- Mutiroom services can be removed if not using multiroom mode
  sound:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: '1'
    ports:
      - 4317:4317
  
  sound-supervisor:
    build: 
      context: .
      dockerfile: ./core/sound-supervisor/Dockerfile.template
    network_mode: host
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1

  # Plugins
  # -- Additional plugins can be added. See https://sound.balenalabs.io/docs/plugins.
  # -- Remove unwanted plugins as needed
  bluetooth:
    build: ./plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: ./plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: ./plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  # https://github.com/balenablocks/hostname
  hostname:
    build: ./core/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: balena
